/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Game.java
 *
 * Created on Jun 21, 2016, 8:45:07 PM
 */

/**
 *
 * @author Parth
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;

public class Game extends javax.swing.JFrame
{
    String [] [] colour = new String [4] [4];
    String [] [] colour1 = new String [4] [4];
    char[][]index=new char[4][4];
    char[][]index1=new char[4][4];
    long score ;

    int direction;

    boolean testCombine [] [] = new boolean[4][4];

    Timer delay1;
    Timer delay2;
    Timer delay3;
    /** Creates new form Game */
    public Game() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        highScoreLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        UndoBtn = new javax.swing.JButton();
        RestartBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        rightBtn = new javax.swing.JButton();
        leftBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        scoreLabel.setBackground(new java.awt.Color(175, 160, 99));
        scoreLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24));
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 17), new java.awt.Color(255, 255, 255))); // NOI18N
        scoreLabel.setOpaque(true);

        highScoreLabel.setBackground(new java.awt.Color(175, 160, 99));
        highScoreLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24));
        highScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        highScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "High Score", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 17), new java.awt.Color(255, 255, 255))); // NOI18N
        highScoreLabel.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(175, 160, 99));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel43.setOpaque(true);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel44.setOpaque(true);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel41.setOpaque(true);

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel42.setOpaque(true);

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel33.setOpaque(true);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel34.setOpaque(true);

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel31.setOpaque(true);

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel32.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel11.setOpaque(true);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel24.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel21.setOpaque(true);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel12.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel14.setOpaque(true);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel23.setOpaque(true);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel22.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 237, 218));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(175, 160, 99));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));

        jLabel26.setBackground(new java.awt.Color(252, 212, 90));
        jLabel26.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("C");
        jLabel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel26.setOpaque(true);

        jLabel27.setBackground(new java.awt.Color(251, 246, 227));
        jLabel27.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("A");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel27.setOpaque(true);

        jLabel28.setBackground(new java.awt.Color(251, 172, 25));
        jLabel28.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("D");
        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel28.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(240, 232, 203));
        jLabel29.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36));
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("B");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(175, 160, 99), 3, true));
        jLabel29.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        UndoBtn.setBackground(new java.awt.Color(175, 160, 99));
        UndoBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        UndoBtn.setForeground(new java.awt.Color(255, 255, 255));
        UndoBtn.setText("Undo");
        UndoBtn.setContentAreaFilled(false);
        UndoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoBtnActionPerformed(evt);
            }
        });

        RestartBtn.setBackground(new java.awt.Color(175, 160, 99));
        RestartBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        RestartBtn.setForeground(new java.awt.Color(255, 255, 255));
        RestartBtn.setText("Restart");
        RestartBtn.setContentAreaFilled(false);
        RestartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartBtnActionPerformed(evt);
            }
        });

        upBtn.setBackground(new java.awt.Color(175, 160, 99));
        upBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        upBtn.setForeground(new java.awt.Color(255, 255, 255));
        upBtn.setText("^");
        upBtn.setBorder(null);
        upBtn.setContentAreaFilled(false);
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.setBackground(new java.awt.Color(175, 160, 99));
        downBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        downBtn.setForeground(new java.awt.Color(255, 255, 255));
        downBtn.setText("v");
        downBtn.setContentAreaFilled(false);
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        rightBtn.setBackground(new java.awt.Color(175, 160, 99));
        rightBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        rightBtn.setForeground(new java.awt.Color(255, 255, 255));
        rightBtn.setText(">");
        rightBtn.setContentAreaFilled(false);
        rightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBtnActionPerformed(evt);
            }
        });

        leftBtn.setBackground(new java.awt.Color(175, 160, 99));
        leftBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18));
        leftBtn.setForeground(new java.awt.Color(255, 255, 255));
        leftBtn.setText("<");
        leftBtn.setContentAreaFilled(false);
        leftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(highScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RestartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UndoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(leftBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightBtn)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(highScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RestartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UndoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed

        direction = 1;

        for(int i=0;i<=3;i++) {
            for(int j = 0;j<=3;j++) {
                testCombine[i][j]=true;
            }
        }

        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                index1[i][j]=index[i][j];
            }

        }
        int key=0;
        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                if(index[i][j]!=' ') {
                    key=1;
                }
            }

        }
        if(key==0)
            JOptionPane.showMessageDialog(this,"Please start the game first");


        goUp();
        valueAssign();
        for(int i =0;i<=3;i++ ) {
            for(int j=0;j<=3;j++) {
                colourAllot(i,j,index [i][j]);
            }
        }
        colourAssign();
        delay();
}//GEN-LAST:event_upBtnActionPerformed

    private void rightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBtnActionPerformed

        direction = 4;

        for(int i=0;i<=3;i++) {
            for(int j = 0;j<=3;j++) {
                testCombine[i][j]=true;
            }
        }

        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                index1[i][j]=index[i][j];
            }

        }
        int key=0;
        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                if(index[i][j]!=' ') {
                    key=1;
                }
            }

        }
        if(key==0)
            JOptionPane.showMessageDialog(this,"Please start the game first");


        goRight();
        valueAssign();
        for(int i =0;i<=3;i++ ) {
            for(int j=0;j<=3;j++) {
                colourAllot(i,j,index [i][j]);
            }
        }
        colourAssign();
        delay();
        // TODO add your handling code here:
}//GEN-LAST:event_rightBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        direction = 2;

        for(int i=0;i<=3;i++) {
            for(int j = 0;j<=3;j++) {
                testCombine[i][j]=true;
            }
        }

        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                index1[i][j]=index[i][j];
            }

        }
        int key=0;
        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                if(index[i][j]!=' ') {
                    key=1;
                }
            }

        }
        if(key==0)
            JOptionPane.showMessageDialog(this,"Please start the game first");


        goDown();
        valueAssign();
        for(int i =0;i<=3;i++ ) {
            for(int j=0;j<=3;j++) {
                colourAllot(i,j,index [i][j]);
            }
        }
        colourAssign();
        delay();
        // TODO add your handling code here:
}//GEN-LAST:event_downBtnActionPerformed

    private void leftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBtnActionPerformed
        direction = 3;

        for(int i=0;i<=3;i++) {
            for(int j = 0;j<=3;j++) {
                testCombine[i][j]=true;
            }
        }

        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                index1[i][j]=index[i][j];
            }

        }
        int key=0;
        for(int i=0;i<=3;i++) {
            for(int j=0;j<=3;j++) {
                if(index[i][j]!=' ') {
                    key=1;
                }
            }

        }
        if(key==0)
            JOptionPane.showMessageDialog(this,"Please start the game first");


        goLeft();
        valueAssign();
        for(int i =0;i<=3;i++ ) {
            for(int j=0;j<=3;j++) {
                colourAllot(i,j,index [i][j]);
            }
        }
        colourAssign();
        delay();

        // TODO add your handling code here:
}//GEN-LAST:event_leftBtnActionPerformed

    private void RestartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartBtnActionPerformed
score=0;

    int a=(int)((Math.random()*4));
    int b=(int)((Math.random()*4));
    int c=(int)((Math.random()*4));
    int d=(int)((Math.random()*4));

    while(a==c&&b==d)
    {
    c=(int)((Math.random()*4));
    d=(int)((Math.random()*4));

    }

    for(int i=0;i<=3;i++)
    {
      for(int j=0;j<=3;j++)
      {
          index[i][j]=' ';
      }
    }

    index[a][b]='A';
    index[c][d]='A';

    valueAssign();

    try
   {
      /* Class.forName("java.sql.DriverManager");
       Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project12","root","1234");
       Statement stmt =(Statement)con.createStatement();
       String query="Delete from Saved_Game;";
       stmt.executeUpdate(query);


    for(int l=0;l<16;l++)
    {
        int i=l/4;
        int j=l%4;
        String query1="Insert into Saved_Game values ('"+i+j+"','"+index[i][j]+"','"+index[i][j]+"');";
        stmt.executeUpdate(query1);
    }

        String query1="Insert into Saved_Game values ('sc','0','0');";
        stmt.executeUpdate(query1);
*/
    }
    catch(Exception e)
   {
       JOptionPane.showMessageDialog(this,e.getMessage());

   }

    for(int i =0;i<=3;i++ ) {
        for(int j=0;j<=3;j++) {
            colourAllot(i,j,index [i][j]);
        }
    }
    colourAssign();        // TODO add your handling code here:
    }//GEN-LAST:event_RestartBtnActionPerformed

    private void UndoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoBtnActionPerformed
/*
    try
    {
         Class.forName("java.sql.DriverManager");
       Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project12","root","1234");
       Statement stmt =(Statement)con.createStatement();

    for(int l=0;l<16;l++)
    {
        int i=l/4;
        int j=l%4;
        String query1="Update Saved_Game set  present = previous where jLabelNo = '"+i+j+"';";
        stmt.executeUpdate(query1);
    }

       String query1="Update Saved_Game set  present = previous where jLabelNo = 'sc';";
        stmt.executeUpdate(query1);

    for(int i=0;i<=3;i++)
   {
       for(int j=0;j<=3;j++)
       {
           String query="Select Present from Saved_Game where jLabelNo = '"+i+j+"';";
           ResultSet rs = stmt.executeQuery(query);
           if(rs.next())
           index[i][j]=(rs.getString("Present")).charAt(0);

       }

   }

           String query="Select Present from Saved_Game where jLabelNo = 'sc';";
           ResultSet rs = stmt.executeQuery(query);
           if(rs.next())
           score=Long.parseLong(rs.getString("Present"));

   valueAssign();
   for(int i =0;i<=3;i++ ) {
        for(int j=0;j<=3;j++) {
            colourAllot(i,j,index [i][j]);
        }
    }
    colourAssign();

    }
    catch(Exception e)
    {
       JOptionPane.showMessageDialog(this,e.getMessage());

    }

  */         // TODO add your handling code here:
    }//GEN-LAST:event_UndoBtnActionPerformed

    /**
    * @param args the command line arguments
    */
       public void colourAllot(int a,int b,char c) {
        switch(c) {
        case 'A':   colour[a][b] = "0xFDF6E3";//251,246,227
                    colour1[a][b] = "0x999999";//153,153,153
                    break;
        case 'B':   colour[a][b] = "0xF0E8CD";//240,232,203
                    colour1[a][b] = "0x999999";//153,153,153
                    break;
        case 'C':   colour[a][b] = "0xFCD45A";//252,212,90
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'D':   colour[a][b] = "0xFDAC19";//251,172,25
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'E':   colour[a][b] = "0xF77A4D";//247,122,77
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'F':   colour[a][b] = "0xFDAC19";//251,172,25 not done
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'G':   colour[a][b] = "0xF7E642";//247,230,66
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'H':   colour[a][b] = "0xF7D942";//247,217,66
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        case 'I':   colour[a][b] = "0xFDAC19";//251,172,25not done
                    colour1[a][b] = "0xFFFFFF";//255,255,255
                    break;
        default:    colour[a][b] = "0xFFFFFF";//247,122,77
                    colour1[a][b]="0xFFFFFF";//255,255,255
                    break;

        }
    }

    public void colourAssign() {
        jLabel11.setForeground(Color.decode(colour1[0][0]));
        jLabel12.setForeground(Color.decode(colour1[0][1]));
        jLabel13.setForeground(Color.decode(colour1[0][2]));
        jLabel14.setForeground(Color.decode(colour1[0][3]));
        jLabel21.setForeground(Color.decode(colour1[1][0]));
        jLabel22.setForeground(Color.decode(colour1[1][1]));
        jLabel23.setForeground(Color.decode(colour1[1][2]));
        jLabel24.setForeground(Color.decode(colour1[1][3]));
        jLabel31.setForeground(Color.decode(colour1[2][0]));
        jLabel32.setForeground(Color.decode(colour1[2][1]));
        jLabel33.setForeground(Color.decode(colour1[2][2]));
        jLabel34.setForeground(Color.decode(colour1[2][3]));
        jLabel41.setForeground(Color.decode(colour1[3][0]));
        jLabel42.setForeground(Color.decode(colour1[3][1]));
        jLabel43.setForeground(Color.decode(colour1[3][2]));
        jLabel44.setForeground(Color.decode(colour1[3][3]));
        jLabel11.setBackground(Color.decode(colour[0][0]));
        jLabel12.setBackground(Color.decode(colour[0][1]));
        jLabel13.setBackground(Color.decode(colour[0][2]));
        jLabel14.setBackground(Color.decode(colour[0][3]));
        jLabel21.setBackground(Color.decode(colour[1][0]));
        jLabel22.setBackground(Color.decode(colour[1][1]));
        jLabel23.setBackground(Color.decode(colour[1][2]));
        jLabel24.setBackground(Color.decode(colour[1][3]));
        jLabel31.setBackground(Color.decode(colour[2][0]));
        jLabel32.setBackground(Color.decode(colour[2][1]));
        jLabel33.setBackground(Color.decode(colour[2][2]));
        jLabel34.setBackground(Color.decode(colour[2][3]));
        jLabel41.setBackground(Color.decode(colour[3][0]));
        jLabel42.setBackground(Color.decode(colour[3][1]));
        jLabel43.setBackground(Color.decode(colour[3][2]));
        jLabel44.setBackground(Color.decode(colour[3][3]));
    }

    public void valueAssign () {
    scoreLabel.setText(""+score);
    jLabel11.setText(""+index[0][0]);
    jLabel12.setText(""+index[0][1]);
    jLabel13.setText(""+index[0][2]);
    jLabel14.setText(""+index[0][3]);

    jLabel21.setText(""+index[1][0]);
    jLabel22.setText(""+index[1][1]);
    jLabel23.setText(""+index[1][2]);
    jLabel24.setText(""+index[1][3]);

    jLabel31.setText(""+index[2][0]);
    jLabel32.setText(""+index[2][1]);
    jLabel33.setText(""+index[2][2]);
    jLabel34.setText(""+index[2][3]);

    jLabel41.setText(""+index[3][0]);
    jLabel42.setText(""+index[3][1]);
    jLabel43.setText(""+index[3][2]);
    jLabel44.setText(""+index[3][3]);

    }

    public void goUp()
    {

        for(int j= 0; j<=3;j++)
        {
            if(index [0][j]==' ')
            {

               for(int l=0;l<3;l++)
               {
                   index[l][j]=index[l+1][j];
               }
               index[3][j]=' ';

            }
            else if(testCombine[0][j]&&testCombine[1][j]&&index [0][j]== index [1][j])
            {

               index[0][j]=(char)(index[1][j]+1);
               index[1][j]=(char)(index[2][j]);
               index[2][j]=(char)(index[3][j]);
               index[3][j]=' ';
               score+=(long)(Math.pow(2,index[0][j]-64));
               testCombine[0][j]=false;
            }
            else if (index[1][j]==' ')
            {

                for(int l=1;l<3;l++)
               {
                   index[l][j]=index[l+1][j];
               }
               index[3][j]=' ';
            }
            else if(testCombine[1][j]&&testCombine[2][j]&&index [1][j]== index [2][j])
            {

               index[1][j]=(char)(index[2][j]+1);
               index[2][j]=(char)(index[3][j]);
               index[3][j]=' ';
               score+=(long)(Math.pow(2,index[1][j]-64));
               testCombine[1][j]=false;
            }
            else if (index[2][j]==' ')
            {

                for(int l=2;l<3;l++)
               {
                   index[l][j]=index[l+1][j];
               }
               index[3][j]=' ';
            }
            else if(testCombine[2][j]&&testCombine[3][j]&&index [2][j]== index [3][j])
            {

               index[2][j]=(char)(index[3][j]+1);
               index[3][j]=' ';
               score+=(long)(Math.pow(2,index[2][j]-64));
               testCombine[2][j] = false;

            }
        }
    }

     public void goDown()
    {

        for(int j= 0; j<=3;j++)
        {
            if(index [3][j]==' ')
            {

               for(int l=3;l>0;l--)
               {
                   index[l][j]=index[l-1][j];
               }
               index[0][j]=' ';

            }
            else if(testCombine[3][j]&&testCombine[2][j]&&index [3][j]== index [2][j])
            {

               index[3][j]=(char)(index[2][j]+1);
               index[2][j]=(char)(index[1][j]);
               index[1][j]=(char)(index[0][j]);
               index[0][j]=' ';
               score+=(long)(Math.pow(2,index[3][j]-64));
               testCombine[3][j]=false;
            }
            else if (index[2][j]==' ')
            {

                for(int l=2;l>0;l--)
               {
                   index[l][j]=index[l-1][j];
               }
               index[0][j]=' ';
            }
            else if(testCombine[2][j]&&testCombine[1][j]&&index [2][j]== index [1][j])
            {

               index[2][j]=(char)(index[1][j]+1);
               index[1][j]=(char)(index[0][j]);
               index[0][j]=' ';
               score+=(long)(Math.pow(2,index[2][j]-64));
               testCombine[2][j]=false;
            }
            else if (index[1][j]==' ')
            {

                for(int l=1;l>0;l--)
               {
                   index[l][j]=index[l-1][j];
               }
               index[0][j]=' ';
            }
            else if(testCombine[1][j]&&testCombine[0][j]&&index [1][j]== index [0][j])
            {

               index[1][j]=(char)(index[0][j]+1);
               index[0][j]=' ';
               score+=(long)(Math.pow(2,index[1][j]-64));
               testCombine[1][j] = false;

            }
        }
    }
public void goLeft()
    {

        for(int i= 0; i<=3;i++)
        {
            if(index [i][0]==' ')
            {

               for(int l=0;l<3;l++)
               {
                   index[i][l]=index[i][l+1];
               }
               index[i][3]=' ';

            }
            else if(testCombine[i][0]&&testCombine[i][1]&&index [i][0]== index [i][1])
            {

               index[i][0]=(char)(index[i][1]+1);
               index[i][1]=(char)(index[i][2]);
               index[i][2]=(char)(index[i][3]);
               index[i][3]=' ';
               score+=(long)(Math.pow(2,index[i][0]-64));
               testCombine[i][0]=false;
            }
            else if (index[i][1]==' ')
            {

                for(int l=1;l<3;l++)
               {
                   index[i][l]=index[i][l+1];
               }
               index[i][3]=' ';
            }
            else if(testCombine[i][1]&&testCombine[i][2]&&index [i][1]== index [i][2])
            {

               index[i][1]=(char)(index[i][2]+1);
               index[i][2]=(char)(index[i][3]);
               index[i][3]=' ';
               score+=(long)(Math.pow(2,index[i][1]-64));
               testCombine[i][1]=false;
            }
            else if (index[i][2]==' ')
            {

                for(int l=2;l<3;l++)
               {
                   index[i][l]=index[i][l+1];
               }
               index[i][3]=' ';
            }
            else if(testCombine[i][2]&&testCombine[i][3]&&index [i][2]== index [i][3])
            {

               index[i][2]=(char)(index[i][3]+1);
               index[i][3]=' ';
               score+=(long)(Math.pow(2,index[i][2]-64));
               testCombine[i][2] = false;

            }
        }
    }
     public void goRight()
    {

        for(int i= 0; i<=3;i++)
        {
            if(index [i][3]==' ')
            {

               for(int l=3;l>0;l--)
               {
                   index[i][l]=index[i][l-1];
               }
               index[i][0]=' ';

            }
            else if(testCombine[i][3]&&testCombine[i][2]&&index [i][3]== index [i][2])
            {

               index[i][3]=(char)(index[i][2]+1);
               index[i][2]=(char)(index[i][1]);
               index[i][1]=(char)(index[i][0]);
               index[i][0]=' ';
               score+=(long)(Math.pow(2,index[i][3]-64));
               testCombine[i][3]=false;
            }
            else if (index[i][2]==' ')
            {

                for(int l=2;l>0;l--)
               {
                   index[i][l]=index[i][l-1];
               }
               index[i][0]=' ';
            }
            else if(testCombine[i][2]&&testCombine[i][1]&&index [i][2]== index [i][1])
            {

               index[i][2]=(char)(index[i][1]+1);
               index[i][1]=(char)(index[i][0]);
               index[i][0]=' ';
               score+=(long)(Math.pow(2,index[i][2]-64));
               testCombine[i][2]=false;
            }
            else if (index[i][1]==' ')
            {

                for(int l=1;l>0;l--)
               {
                   index[i][l]=index[i][l-1];
               }
               index[i][0]=' ';
            }
            else if(testCombine[i][1]&&testCombine[i][0]&&index [i][1]== index [i][0])
            {

               index[i][1]=(char)(index[i][0]+1);
               index[i][0]=' ';
               score+=(long)(Math.pow(2,index[i][1]-64));
               testCombine[i][1] = false;

            }
        }
    }

    public void delay() {
        delay1 = new Timer();
        delay2 = new Timer();
        delay3 = new Timer();
        delay1.schedule(new execute1(), 200);
        delay2.schedule(new execute1(),400);
        delay3.schedule(new execute2(),600);
    }

    class execute1 extends TimerTask {
        public void run() {
            switch(direction) {
                case 1: goUp();
                        valueAssign();
                        for(int i =0;i<=3;i++ )
                        {
                            for(int j=0;j<=3;j++)
                            {
                                colourAllot(i,j,index [i][j]);
                            }
                        }
                        colourAssign();
                        break;
                        case 2: goDown();
                        valueAssign();
                        for(int i =0;i<=3;i++ )
                        {
                            for(int j=0;j<=3;j++)
                            {
                                colourAllot(i,j,index [i][j]);
                            }
                        }
                        colourAssign();
                        break;
                        case 3: goLeft();
                        valueAssign();
                        for(int i =0;i<=3;i++ )
                        {
                            for(int j=0;j<=3;j++)
                            {
                                colourAllot(i,j,index [i][j]);
                            }
                        }
                        colourAssign();
                        break;
                        case 4: goRight();
                        valueAssign();
                        for(int i =0;i<=3;i++ )
                        {
                            for(int j=0;j<=3;j++)
                            {
                                colourAllot(i,j,index [i][j]);
                            }
                        }
                        colourAssign();
                        break;

            }

        }
    }
    class execute2 extends TimerTask {
        public void run() {
            try
{
   int flag=0;
   for(int i=0;i<=3;i++)
   {
       for(int j=0;j<=3;j++)
       {
           if(index1[i][j]!=index[i][j])
               flag = 1;
       }

   }

char add1=(char)(65+(int)((Math.random()*2)));
char add2=(char)(65+(int)((Math.random()*3)));
if(flag==1)
{
while(true)
{
    int a=(int)((Math.random()*4));
    int b=(int)((Math.random()*4));
    if(index[a][b]==' ')
    {
        if (score<150)
            index[a][b]='A';
        else if(score>=150&&score<500)
            index[a][b]=add1;
        else
            index[a][b]=add2;
        break;
    }
}

}

   valueAssign();
      for(int i =0;i<=3;i++ ) {
        for(int j=0;j<=3;j++) {
            colourAllot(i,j,index [i][j]);
        }
    }
   colourAssign();


   /*
       Class.forName("java.sql.DriverManager");
       Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/project12","root","1234");
       Statement stmt =(Statement)con.createStatement();


    if(flag==1)
    {
    for(int l=0;l<16;l++)
    {
        int i=l/4;
        int j=l%4;
        String query1="Update Saved_Game set previous = present where jLabelNo = '"+i+j+"';";
        stmt.executeUpdate(query1);
        String query="Update Saved_Game set present = '"+index[i][j]+"' where jLabelNo = '"+i+j+"';";
        stmt.executeUpdate(query);
    }
    }

        String query1="Update Saved_Game set previous = present where jLabelNo = 'sc';";
        stmt.executeUpdate(query1);
        String query="Update Saved_Game set present = '"+score+"' where jLabelNo = 'sc';";
        stmt.executeUpdate(query);

    */

    }
    catch(Exception e)
    {
       //JOptionPane.showMessageDialog(this, e.getMessage());

    }
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RestartBtn;
    private javax.swing.JButton UndoBtn;
    private javax.swing.JButton downBtn;
    private javax.swing.JLabel highScoreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton leftBtn;
    private javax.swing.JButton rightBtn;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables

}
